# Last updated: 2026-02-23
name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      free_disk_space:
        description: 'Free disk space before build (adds ~1-2 min, useful for large images)'
        type: boolean
        default: false
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  release:
    types: [published]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.build-and-push.outputs.digest }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Free Disk Space (Ubuntu)
        # To always run, remove the if condition below
        # To never run, remove the entire step
        if: ${{ inputs.free_disk_space || (github.event_name == 'release' && github.event.action == 'published') || github.ref_type == 'tag' }}
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main as of 2026-02-23
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ github.event_name == 'release' && github.event.action == 'published' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          sbom: ${{ github.event_name == 'release' && github.event.action == 'published' }}
          # build-args: |
          #   MY_ARG=value
          # dockerfile: Dockerfile.custom
  trivy-scan:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build.outputs.image-digest }}
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Display vulnerability summary and fail on CRITICAL
        if: always()
        run: |
          echo "## Vulnerability Summary"
          jq -r '.Results[]? | select(.Vulnerabilities) | .Vulnerabilities | group_by(.Severity) | map({severity: .[0].Severity, count: length}) | .[] | "\(.severity): \(.count)"' trivy-results.json || echo "No vulnerabilities found"
          echo ""
          echo "To see full vulnerability details, run locally:"
          echo "trivy image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build.outputs.image-digest }}"
          if jq -e '.Results[]? | select(.Vulnerabilities) | .Vulnerabilities[] | select(.Severity == "CRITICAL")' trivy-results.json > /dev/null; then
            echo ""
            echo "::error::CRITICAL vulnerabilities found! Build failed."
            exit 1
          fi
